version: '3.8'
services:
  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    volumes:
      - mysql-queenless-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - queenless-pollination-platform

  shopping-backend:
    build: 
      context: ./shopping/backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${ROOT_PASSWORD}
      DB_NAME: ${DATABASE}
    networks:
      - queenless-pollination-platform

  shopping-frontend:
    build:
      context: ./shopping/frontend
      args:
        - API_URL=http://shopping-backend:5000/api/:path*
    ports:
      - "3000:3000"
    depends_on:
      - shopping-backend
    networks:
      - queenless-pollination-platform

  routing-backend:
    build:
      context: ./routing/backend
    ports:
      - "6000:6000"
    depends_on:
      - db
    networks:
      - queenless-pollination-platform
volumes:
  mysql-queenless-data:

networks:
  queenless-pollination-platform:
    driver: bridge